services:
  freqtrade:
    build: .
    image: my-freqtrade:latest
    volumes:
      - ./freqtrade:/freqtrade/freqtrade
      - ./user_data:/freqtrade/user_data
      - ./market_data:/freqtrade/market_data
    environment:
      - PYTHONPATH=/freqtrade
